import { User } from "./User";

export interface Task {
  taskId: number; // for now (later will be an autogenerated key)
  projectId: number; // for now (later will be a relationship to an Id in the Project table)
  taskTitle: string;
  taskDescription: string;
  taskStatus: string;
  taskCreator: User;
  taskTeam: User[];
  menuSection: string;
}
