export interface User {
  userId: number; // for now (later will be an autogenerated key)
  userName: string;
  userEmail: string;
  userImageURL: string;
}

export interface UserState {
  status: any;
  userInformation: User | null;
}
